# Master Playbook for Lune.su server

- name: Install system updates
  ansible.builtin.import_playbook: ./system/update.yaml

- name: Install Podman and Compose
  ansible.builtin.import_playbook: ./container/podman.yaml

- name: Install Firewall and settings
  ansible.builtin.import_playbook: ./security/firewall.yaml

- name: Install Nftables and settings
  ansible.builtin.import_playbook: ./security/users.yaml

#- name: Install Apparmor and settings
#  ansible.builtin.import_playbook: ./security/apparmor.yaml

- name: Install Lune.su
  ansible.builtin.import_playbook: ./app/lune.yaml

- name: New Users
  ansible.builtin.import_playbook: ./security/users.yaml

- name: Start Lune.su
  ansible.builtin.import_playbook: ./app/start.yaml
