services:
  nginx:
    image: docker.io/laimick/luneback:latest
    volumes:
      - /home/lune/server/ssl/:/etc/nginx/ssl/
    ports:
      - "443:443"
    networks:
      - lune_net
    depends_on:
      - lune1
      - lune2
      - lune3
    restart: unless-stopped

  lune1:
    image: docker.io/laimick/luneapp:latest
    networks:
      - lune_net
    expose:
      - 3000
    restart: unless-stopped
  lune2: 
    image: docker.io/laimick/luneapp:latest
    networks:
      - lune_net
    expose:
      - 3000
    restart: unless-stopped
  lune3: 
    image: docker.io/laimick/luneapp:latest
    networks:
      - lune_net
    expose:
      - 3000
    restart: unless-stopped

networks:
  lune_net:
    driver: bridge
