- name: Running containers on the server
  hosts: lune
  become: true

  tasks:
    - name: Copy Composefile
      copy:
        src: "{{ PROJECT_DIR }}/podman/compose/compose.yaml"
        dest: /home/lune/server/

    - name: Copy App
      copy:
        src: "{{ item }}"
        dest: /home/lune/server/app/
      with_fileglob:
        - "{{ PROJECT_DIR }}/podman/app/*"

    - name: Copy Images
      copy:
        src: "{{ item }}"
        dest: /home/lune/server/app/assets/images/
      with_fileglob:
        - "{{ PROJECT_DIR }}/podman/app/assets/images/*"

    - name: Copy Styles
      copy:
        src: "{{ item }}"
        dest: /home/lune/server/app/assets/styles/
      with_fileglob:
        - "{{ PROJECT_DIR }}/podman/app/assets/styles/*"

    - name: Copy Nginx
      copy:
        src: "{{ item }}"
        dest: /home/lune/server/nginx/
        follow: true
      with_fileglob:
        - "{{ PROJECT_DIR }}/podman/nginx/*"

    - name: Copy SSL
      copy:
        src: "{{ item }}"
        dest: /home/lune/server/nginx/ssl/
        follow: true
      with_fileglob:
        - "{{ PROJECT_DIR }}/podman/nginx/ssl/*"

    - name: Copy Bash Script
      copy:
        src: "{{ PROJECT_DIR }}/scripts/start.sh"
        dest: /home/lune/server/
        mode: "0777"
        owner: lune
