- name: Install Podman
  hosts: lune
  become: true

  tasks:
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: latest

    - name: Enabled and start service
      ansible.builtin.service:
        name: podman
        state: started
        enabled: true

    - name: Install podman-compose
      ansible.builtin.package:
        name: podman-compose
        state: latest

    - name: Settings podman
      ansible.builtin.copy:
        src: "{{ PROJECT_DIR }}/infrastructure/podman/registries.conf"
        dest: /etc/containers/registries.conf
