- name: Install Podman
  hosts: lune
  become: true

  tasks:
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: latest

    - name: Enabled and started service
      ansible.builtin.service:
        name: podman
        state: started
        enabled: true

    - name: Install python3
      ansible.builtin.package:
        name: python3
        state: latest

    - name: Install python3-pip
      ansible.builtin.package:
        name: python3-pip
        state: latest

    - name: Install python3-devel
      ansible.builtin.package:
        name: python3-devel
        state: latest

    - name: Install pyyaml via pip3
      ansible.builtin.pip:
        name: pyyaml

    - name: Install podman-compose
      ansible.builtin.pip:
        name: podman-compose

    - name: Settings podman
      ansible.builtin.copy:
        src: "{{ PROJECT_DIR }}/infrastructure/podman/registries.conf"
        dest: /etc/containers/registries.conf
