services:
  nginx:
    build: ./nginx/.
    ports:
      - "443:443"
    networks:
      - lune_net
    restart: unless-stopped

  lune:
    build: ./app/.
    ports:
      - "8080:8080"
    networks:
      - lune_net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - lune_net

networks:
  lune_net:
    driver: bridge
