services:
  nginx:
    build: ./nginx/.
    ports:
      - "443:443"
    networks:
      - lune_net
    restart: unless-stopped

  lune:
    build: ./app/.
    networks:
      - lune_net
    restart: unless-stopped

  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   restart: unless-stopped
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - lune_net

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #     - "--web.console.libraries=/etc/prometheus/console_libraries"
  #     - "--web.console.templates=/etc/prometheus/consoles"
  #     - "--web.enable-lifecycle"
  #   expose:
  #     - 9090
  #   networks:
  #     - lune_net

  #   restart: unless-stopped

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   # container_name: node-exporter
  #   restart: unless-stopped
  #   volumes:
  #     # - /proc:host/proc:ro
  #     - /sys:hosts/sys:ro
  #     - /:/rootfs:ro
  #   expose:
  #     - 9100
  #   networks:
  #     - lune_net

networks:
  lune_net:
    driver: bridge

volumes:
  prometheus_data: {}
