name: Check Build ContainerFile

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install podman
        run: |
          apt install -y podman

      - name: Checking if nginx/containerfile build works
        run: |
          podman build -f ./images/nginx/.
